version: '3'
services:
  multinet-server:
    container_name: multinet-server
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /tmp/multinet/logs:/var/multinet/logs/
  gremlin-server:
    image: tinkerpop/gremlin-server:3.3
    container_name: gremlin-server
    ports:
      - "8182:8182"
    command: ["conf/gremlin-server-modern-py.yaml"]
