version: '3'
services:
  multinet-server:
    container_name: multinet-server
    build: .
    ports:
      - "8080:8080"
    environment:
      - MULTINET_ROOT_PASSWORD=${MULTINET_ROOT_PASSWORD:-openSesame}
      - ARANGO_HOST=${ARANGO_HOST:-arangodb}
      - ARANGO_PORT=${ARANGO_PORT:-8529}
  arangodb:
    image: arangodb/arangodb:3.4.3
    container_name: arangodb
    ports:
      - "${ARANGO_PORT:-8529}:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=${MULTINET_ROOT_PASSWORD:-openSesame}
