version: '3'
services:
  multinet-server:
    container_name: multinet-server
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /tmp/multinet/logs:/var/multinet/logs/
  arangodb:
    image: arangodb/arangodb:3.4.3
    container_name: arangodb
    ports:
      - "8529:8529"
    volumes:
      - ./data:/data
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_ROOT_PASSWORD:-openSesame}
